### ISSUE TITLE
Add JSDoc comments

### ISSUE THREAD

**Issue by ktmouk** [factory-js/factory-js#27]
### Describe your proposal

We want to add JSDoc comments so that we can easily check how to use the methods in editor such as VSCode.

Ideally, each comment includes:
  - A concise description of one or two lines.
  - `@param`
  - `@example`

### Todo
While we want to add JSDoc comments to all public methods below, we welcome PRs that add JSDocs to some of the public methods.

- [ ] [props](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L55)
- [ ] [vars](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L65)
- [ ] [traits](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L75)
- [ ] [use](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L85)
- [ ] [after](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L104)
- [ ] [build](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L111)
- [ ] [buildList](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L115)
- [ ] [create](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L123)
- [ ] [createList](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L129)
- [ ] [def](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L137)
- [ ] [define](https://github.com/factory-js/factory-js/blob/4129ce61e166d4ccd703ab4e5f72d8e4dfbf69c3/packages/factory/src/factory.ts#L173)

### Example (drizzle-orm)
https://github.com/drizzle-team/drizzle-orm/blob/a78eefe08e127922565486143e0150a718b27e8a/drizzle-orm/src/mysql-core/db.ts#L407-L425

<img width="415" src="https://github.com/factory-js/factory-js/assets/17381979/8c25f613-0643-4433-9230-2dfd48acf94e">
